---
title: "Power Analysis Project 3"
author: "Annika Frach"
date: "`r Sys.Date()`"
output: html_document
---


```{r }
library(pwrss)

```
### Power analysis based on values from previous research

```{r pressure, echo=FALSE}

## workaholism and normal personality (r2 change when adding personality)
pwrss.f.regression(r2 = .13,
                   k = 29, # number of total predictors
                   power = 0.90,
                   alpha = 0.05)


### video game and normal personality (big5) (Andreassen et al., 2013)


pwrss.f.regression(r2 = .061,
                   k = 6, # number of total predictors
                   power = 0.90,
                   alpha = 0.05)


### deceitfulness to predict gambling (Pizzini)
pwrss.f.regression(r2 = .049,
                   k = 4, # number of total predictors
                   power = 0.90,
                   alpha = 0.05)




### deceitfulness and perceptual dysregulation to predict gambling (Pizzini)
pwrss.f.regression(r2 = .071,
                   k = 5, # number of total predictors
                   power = 0.90,
                   alpha = 0.05)


##Disinhibition and Gambling (Nigro et al., 2018)


pwrss.f.regression(r2 = 0.208,
                   k = 4, # number of total predictors
                   power = 0.90,
                   alpha = 0.05)



###Internet (Gervasi et al., 2017)
pwrss.f.regression(r2 = 0.305,
                   k = 9, # number of total predictors
                   power = 0.90,
                   alpha = 0.05)

##PiD-5 and overworking (Valls et al., 2023) calculated based on adjusted r squared: 1 - (1 - .05) * (235 - 5 - 1) / (235 - 1) = 0.07029915

pwrss.f.regression(r2 = 0.07,
                   k = 5, # number of total predictors
                   power = 0.90,
                   alpha = 0.05)


```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
